### ISSUE TITLE
string vs class injections

### ISSUE THREAD

**Issue by amcdnl** [lgvo/di-decorators#7]
Any plans for support something like this:

```
@Inject("foo")
class Bar {
    constructor(foo: Foo) {
        this.foo = foo;
    }
}
```

then later register it like:

```
var injector = new Injector([
    bind("foo").to(Foo)
]);
```

Idea from here: https://github.com/footballradar/jecht

**Comment by lgvo** [comment]
Actually I really dislike the use of string's for dependency injection.

Can you elaborate a use case for that?

**Comment by amcdnl** [comment]
1. Its a little nicer to write, I don't have to constantly include the injected class everywhere.
2. The main thing about IoC is unit testing, how do you rewire your factory/repository/etc when you go to test it?  For instance, if I make the register like so, I can rebind it during my test preparation.

**Comment by lgvo** [comment]
You can bind to a mock using:

``` javascript
provide(MyClass).as(function() {
    return {
          name: 'mock'
    };
});
```

If anything for testing and rebind is missing I think it's a good a ideia to make it better.
But I really dislike strings in DI and is one of the reason's I end up writing a lib to do it.
